
title: Niavok
description: Niavok home page and blog.
url: http://niavok.com/
permalink: ':title/'
favicon:     "images/favicon.ico"
markdown: kramdown
baseurl: ""


sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-78944390-1

# Comments
disqus-shortname: niavok-blog

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]

prose:
  rooturl: '_posts'
  siteurl: 'http://niavok;com/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          value: "Niavok"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: ""
      - name: "description"
        field:
          label: "Description"
          element: "text"
          value: ""
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "display_date"
        field:
          label: "Display date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "img"
        field:
          label: "Image"
          element: "text"
          value: "none.png"
      - name: "color"
        field:
          label: "Color"
          element: "text"
          value: "FFFFFF"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          placeholder: "Choose categories"
          options:
            - name: "Sciences"
              value: "sciences"
            - name: "Games"
              value: "games"
            - name: "Work"
              value: "work"
            - name: "Tools"
              value: "tools"
